name: "Android Apk CI"
branding:
  icon: "package"
  color: "red"
description: "Build & Publish Debug APK on Github"
author: "yuanjinsong"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of APK to release."
runs:
  using: "docker"
  image: "Dockerfile"
